# Generated by Django 3.2.9 on 2021-12-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P10Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('device_message', models.CharField(max_length=200)),
                ('device_brightness', models.IntegerField()),
                ('device_scrolling_speed', models.IntegerField()),
            ],
        ),
    ]
